#!/bin/sh

# Clear the last preview (if any)
$HOME/.config/lf/image clear

# Calculate where the image should be placed on the screen.
num=$(printf "%0.f\n" "`echo "$(tput cols) / 2" | bc`")
numb=$(printf "%0.f\n" "`echo "$(tput cols) - $num - 1" | bc`")
numc=$(printf "%0.f\n" "`echo "$(tput lines) - 2" | bc`")

case "$1" in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    # *.pdf) pdftotext "$1" -;;
		*.pdf)
			CACHE=$(mktemp /tmp/thumbcache.XXXXX)
			pdftoppm -png -f 1 -singlefile "$1" "$CACHE"
			$HOME/.config/lf/scripts/imagePv draw "$CACHE.png" $num 1 $numb $numc
			;;
		*.bmp|*.jpg|*.JPG|*.jpeg|*.JPEG|*.png|*.PNG)
			$HOME/.config/lf/scripts/imagePv draw "$1" $num 1 $numb $numc
			;;
		*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) exiftool "$1";;
		*.avi|*.mkv|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
			CACHE=$(mktemp /tmp/thumbcache.XXXXX)
			ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
			$HOME/.config/lf/scripts/imagePv draw "$CACHE" $num 1 $numb $numc
			;;
		*) ~/.config/lf/scripts/filePv $1;;
esac
