source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/keymaps.vim
source $HOME/.config/nvim/macros.vim
source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/theme.vim
source $HOME/.config/nvim/coc.vim
source $HOME/.config/nvim/fzf.vim
source $HOME/.config/nvim/floaterm.vim
source $HOME/.config/nvim/ghost.vim
source $HOME/.config/nvim/fold.vim
source $HOME/.config/nvim/workspace.vim
source $HOME/.config/nvim/compile.vim
