#! /bin/sh

bspc rule -r "*"

sxhkd &
xmodmap ~/.Xmodmap &
polybar example &
picom &
~/bin/setbg &
nm-applet &
bluetooth-applet &
/usr/lib/geoclue-2.0/demos/agent &
redshift-gtk &
~/.config/polybar/spotify/launchlistener.sh &

#Wallpaper
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          15
bspc config top_padding         30
bspc config focus_follows_pointer true

# Border Colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#FF00FF"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

#bspc config normal_frame_opacity 0.75
#bspc config focused_frame_opacity 0.75

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Desktops configs
bspc rule -a Google-chrome desktop=^2
bspc rule -a Code desktop=^3
bspc rule -a Spotify desktop=^9
bspc rule -a mpv state=floating
bspc rule -a Onboard state=floating
bspc rule -a java-lang-Thread state=floating

# General configs
# Mouse Pad
synclient TapButton1=1 TapButton2=3

#Keyboard acceleration
# First Arg : delay
# Second Arg : interval
xset r rate 180 40 

# Compose key to be right alt
setxkbmap -option compose:ralt
