#! /bin/sh

bspc rule -r "*"

killall redshift-gtk &
killall redshift &
pkill -USR1 -x sxhkd
sxhkd &
~/bin/toStart &
polybar -r example &
nm-applet &
picom &
redshift-gtk &
~/bin/setbg &
~/bin/clipmanager &

#Wallpaper
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          15
bspc config top_padding         30
bspc config focus_follows_pointer false

# Border Colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#FF00FF"

#bspc config normal_frame_opacity 0.75
#bspc config focused_frame_opacity 0.75

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Desktops configs
bspc rule -a Google-chrome desktop=^2
bspc rule -a Code desktop=^3
bspc rule -a Spotify desktop=^9
bspc rule -a mpv state=floating
bspc rule -a Onboard state=floating
bspc rule -a xdman-Main desktop=^8 state=floating
bspc rule -a Gimp desktop=^4
bspc rule -a figma-linux dekstop=^3
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Ranger state=floating
bspc rule -a Cmus desktop=^4 state=floating follow=on
bspc rule -a Note dekstop=^5 state=floating follow=on
bspc rule -a Sxiv state=floating
bspc rule -a Deluge-gtk state=floating
bspc rule -a jetbrains-studio state=floating dekstop=^7
bspc rule -a zoom dekstop=^3
bspc rule -a Floater state=floating
bspc rule -a Yad state=floating
bspc rule -a WATCHED dekstop=^1
bspc rule -a Calculator.Skia.Gtk state=floating rectangle=400x550+450+100

# General configs
# Mouse Pad
synclient TapButton1=1 TapButton2=3

#Keyboard acceleration
# First Arg : delay
# Second Arg : interval
xset r rate 180 40 
