# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  # Lorems
  - trigger: ":lrs"
    replace: "Non molestias dolores molestiae laudantium totam.!"

  - trigger: ":lrp1"
    replace: "Quis earum qui. Sint ipsum ut dicta quae. Ut rerum unde. Voluptate vel autem non modi vitae quasi. Doloremque sed ipsa iure in natus perspiciatis nulla."

  - trigger: ":lrp2"
    replace: "Architecto veniam natus sint. Fugiat reiciendis ex quo labore et ut. Sunt eum necessitatibus quam a dolores non explicabo. Repellat voluptatem id. Ullam eligendi dolores consequuntur in. Velit alias libero magnam quo praesentium numquam sunt velit. Quis praesentium quo sequi occaecati quaerat inventore. Laboriosam rerum facere culpa est. Repellendus sed in nesciunt libero natus similique laudantium. In consequuntur in aut nostrum velit architecto exercitationem non. Necessitatibus voluptatem explicabo sed dolorem magnam ut. Voluptatibus adipisci odit amet atque sequi iusto adipisci. Est omnis quia consequatur neque rem magnam nesciunt. Eos ad eligendi earum. Et sequi et voluptate ut exercitationem pariatur. Possimus et suscipit voluptatem quo. Quisquam dolor omnis. Ut et quod."

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
