#!/bin/sh
while read file
do
  case "$1" in
  "w") ~/bin/setbg "$file" & ;;
  "r")
		convert -rotate 90 "$file" "$file" ;;
  "R")
		convert -rotate -90 "$file" "$file" ;;
  "f")
		convert -flop "$file" "$file" ;;
  "C-d")
    trash-put "$file" && notify-send "Image '$file' deleted" ;;
  "C-c")
    echo -n "$file" | xclip -selection clipboard && notify-send "Image '$file' copied to clipboard";;
  esac
done
