[env]
TERM = "xterm-256color"
 
[font]
size = 17

[font.normal]
family = "FiraCode Nerd Font"

[window]
dynamic_padding = true
# padding = {x = 10, y = 0}
opacity = 0.8
blur = true
decorations = "buttonless"

[keyboard]
[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "H"
mods = "Alt|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Up"
mods = "Alt"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "Down"
mods = "Alt"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "U"
mods = "Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
action = "ScrollPageDown"
